// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANTtKEsy46br9IOSUff99_qW2ePTXI5ls',
    appId: '1:225688290928:web:630fb2848bab045ffd16b5',
    messagingSenderId: '225688290928',
    projectId: 'resqube-1b969',
    authDomain: 'resqube-1b969.firebaseapp.com',
    databaseURL: 'https://resqube-1b969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resqube-1b969.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPnRPiJBJTT6HjG5kR8gowXxdiGGAU3jU',
    appId: '1:225688290928:android:5e40320cae78f785fd16b5',
    messagingSenderId: '225688290928',
    projectId: 'resqube-1b969',
    databaseURL: 'https://resqube-1b969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resqube-1b969.appspot.com',
  );
}
